# Generated by Django 4.2.6 on 2024-03-07 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalF', '0003_money_remove_expence_itype_remove_income_itype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='for_month',
            field=models.DateField(default=datetime.datetime(2024, 3, 7, 13, 51, 9, 522557, tzinfo=datetime.timezone.utc)),
        ),
    ]
