# Generated by Django 4.2.6 on 2024-03-15 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalF', '0008_alter_budget_for_month_alter_budget_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='user',
        ),
        migrations.AlterField(
            model_name='budget',
            name='for_month',
            field=models.DateField(default=datetime.datetime(2024, 3, 15, 17, 17, 24, 653499, tzinfo=datetime.timezone.utc)),
        ),
    ]
