# Generated by Django 4.2.6 on 2024-03-16 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalF', '0012_budget_user_alter_budget_for_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='money',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='budget',
            name='for_month',
            field=models.DateField(default=datetime.datetime(2024, 3, 16, 17, 5, 41, 253574, tzinfo=datetime.timezone.utc)),
        ),
    ]
