# Generated by Django 4.2.6 on 2024-03-26 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalF', '0014_rename_name_money_discription_alter_budget_for_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='money',
            old_name='type',
            new_name='Mtype',
        ),
        migrations.AlterField(
            model_name='budget',
            name='for_month',
            field=models.DateField(default=datetime.datetime(2024, 3, 26, 10, 28, 32, 820285, tzinfo=datetime.timezone.utc)),
        ),
    ]
