# Generated by Django 4.2.6 on 2024-03-26 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalF', '0015_rename_type_money_mtype_alter_budget_for_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='for_month',
            field=models.DateField(default=datetime.datetime(2024, 3, 26, 10, 53, 57, 533365, tzinfo=datetime.timezone.utc)),
        ),
    ]
