# Generated by Django 4.2.6 on 2024-03-26 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalF', '0016_alter_budget_for_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='for_month',
            field=models.DateField(default=datetime.datetime(2024, 3, 26, 11, 19, 14, 236647, tzinfo=datetime.timezone.utc)),
        ),
    ]
